name: 📤 Upload OTA JSON to FTP

on:
  workflow_dispatch:

jobs:
  upload-ota:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - rockchip
          - x86_64

    steps:
      - name: Set up workspace
        run: |
          sudo timedatectl set-timezone 'Asia/Shanghai'
          mkdir -p openwrt/ota

      - name: Download ota.json
        run: |
          if [ "${{ matrix.target }}" = "rockchip" ]; then
            curl -L -o openwrt/ota/ota.json https://github.com/zhiern/ZeroWrt-Action/releases/download/Rockchip/ota.json
          elif [ "${{ matrix.target }}" = "x86_64" ]; then
            curl -L -o openwrt/ota/ota.json https://github.com/zhiern/ZeroWrt-Action/releases/download/X86_64/ota.json
          fi
        
      - name: Upload OTA File to FTP
        uses: zhiern/FTP-Deploy-Action@master
        with:
          server: ${{ secrets.ftp_address }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: ${{ secrets.file_path }}/${{ matrix.target }}/
          local-dir: openwrt/ota/
          dangerous-clean-slate: true
