name: Upload to FTP (Rockchip)

on:
  workflow_dispatch:

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    env:
      FIRMWARE_PATH: firmware

    steps:
      - name: 创建工作目录
        run: mkdir -p ${{ env.FIRMWARE_PATH }}

      - name: 下载 Release 文件
        run: |
          TAG="Rockchip"
          REPO="zhiern/ZeroWrt-Action"
          API_URL="https://api.github.com/repos/${REPO}/releases/tags/${TAG}"

          echo "Fetching assets from ${API_URL}"

          curl -sSL $API_URL | \
            jq -r '.assets[].browser_download_url' | \
            while read url; do
              echo "Downloading $url"
              curl -L "$url" -o "${{ env.FIRMWARE_PATH }}/$(basename $url)"
            done

      - name: 显示下载的文件
        run: ls -lh ${{ env.FIRMWARE_PATH }}

      - name: Upload FTP
        uses: zhiern/FTP-Deploy-Action@master
        with:
          server: ${{ secrets.ftp_address }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: ${{ secrets.file_path }}/rockchip/
          local-dir: ${{ env.FIRMWARE_PATH }}/
          dangerous-clean-slate: true
